name: Deploy Squiggle Web to AWS

on:
  push:
    branches: [ main ]
    paths:
      - 'squiggle-web/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'squiggle-web/**'

env:
  AWS_REGION: us-east-1
  S3_BUCKET: your-squiggle-app-bucket
  CLOUDFRONT_DISTRIBUTION_ID: your-cloudfront-distribution-id

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: squiggle-web/squiggle-ui/package-lock.json
    
    - name: Install dependencies
      run: |
        cd squiggle-web/squiggle-ui
        npm ci
    
    - name: Build application
      run: |
        cd squiggle-web/squiggle-ui
        npm run build
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Deploy to S3
      run: |
        aws s3 sync squiggle-web/squiggle-ui/dist/ s3://${{ env.S3_BUCKET }} --delete
    
    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*" 